const eventsByType = {
    "Performing Arts": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Literary Events": {
      image: "",
      tag: ["All", "Technical"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Technical Events": {
      image: "",
      tag: ["All", "Technical"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Fashion & Lifestyle:": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Sports and eSports": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "HR Club": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "WE Club": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Sports Club": {
      image: "",
      tag: ["All", "Cultural + fun"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Finearts Club": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Literary Club": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Melodia Club": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Media Club": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "CDC Club": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
    "Mask Club": {
      image: "",
      tag: ["All"],
      events: [
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
        {
          name: "",
          image: "",
          description: "",
          registrationLink: "",
          whatsappLink: "",
        },
      ],
    },
};

export default eventsByType;